CREATE STREAM bird_combined AS
SELECT BIRD_STREAM_3.ID, BIRD_STREAM_3.FARM, BIRD_STREAM_3.BIRD_ID, BIRD_STREAM_3.LONGITUDE, BIRD_STREAM_3.LATITUDE, BIRD_STREAM_3.DATE_TIME, BIRD_STREAM_3.FILE_PATH, BIRD_NAME_3.BIRD_ID AS BIRD_ID, BIRD_NAME_3.BIRD_NAME 
FROM  BIRD_STREAM_3
JOIN  BIRD_NAME_3
ON BIRD_STREAM_3.BIRD_ID = BIRD_NAME_3.BIRD_ID
EMIT CHANGES;