CREATE STREAM whale_combined AS
SELECT WHALE_STREAM_2.ID, WHALE_STREAM_2.FARM, WHALE_STREAM_2.WHALE_ID, WHALE_STREAM_2.LONGITUDE, WHALE_STREAM_2.LATITUDE, WHALE_STREAM_2.DATE_TIME, WHALE_STREAM_2.FILE_PATH, WHALE_NAME_2.WHALE_ID AS WHALE_ID, WHALE_NAME_2.WHALE_NAME 
FROM  WHALE_STREAM_2
JOIN  WHALE_NAME_2
ON WHALE_STREAM_2.WHALE_ID = WHALE_NAME_2.WHALE_ID
EMIT CHANGES;