CREATE STREAM ALL_STREAM WITH (KAFKA_TOPIC='ALL_STREAM', PARTITIONS=1, REPLICAS=1) AS SELECT
  SHEEP_COMBINED.SHEEP_STREAM_1_SHEEP_ID ANIMAL_ID_KEY,
  SHEEP_COMBINED.SHEEP_ID ANIMAL_ID,
  SHEEP_COMBINED.SHEEP_NAME ANIMAL_NAME,
  SHEEP_COMBINED.FARM FARM,
  SHEEP_COMBINED.LONGITUDE LONGITUDE,
  SHEEP_COMBINED.LATITUDE LATITUDE,
  SHEEP_COMBINED.DATE_TIME DATE_TIME,
  SHEEP_COMBINED.FILE_PATH FILE_PATH
FROM SHEEP_COMBINED SHEEP_COMBINED
EMIT CHANGES;

INSERT INTO ALL_STREAM SELECT
  WHALE_STREAM_2_WHALE_ID ANIMAL_ID_KEY,
  WHALE_ID ANIMAL_ID, 
  WHALE_NAME ANIMAL_NAME,
  FARM,
  LONGITUDE,
  LATITUDE,
  DATE_TIME,
  FILE_PATH
FROM  WHALE_COMBINED
EMIT CHANGES;

INSERT INTO ALL_STREAM SELECT
  BIRD_STREAM_3_BIRD_ID ANIMAL_ID_KEY,
  BIRD_ID ANIMAL_ID, 
  BIRD_NAME ANIMAL_NAME,
  FARM,
  LONGITUDE,
  LATITUDE,
  DATE_TIME,
  FILE_PATH
FROM  BIRD_COMBINED
EMIT CHANGES;